nodes:
  - Trigger
  - Search
  - Slice
  - Details
  - AI
  - Store
  - Invite
  - Wait
connections:
  Trigger: [Search]
  Search: [Slice]
  Slice: [Details]
  Details: [AI, Store]
  AI: [Store]
  Store: [Invite]
  Invite: [Wait]
  Wait: [Details]
